package com.xudaweb.distributed.lock.dal.model;

import java.util.Date;

public class ResourceLock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_lock.id
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_lock.resource_name
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_lock.node_info
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    private String nodeInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_lock.count
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    private Long count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_lock.desc
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_lock.update_time
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_lock.create_time
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_lock.id
     *
     * @return the value of resource_lock.id
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_lock.id
     *
     * @param id the value for resource_lock.id
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_lock.resource_name
     *
     * @return the value of resource_lock.resource_name
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_lock.resource_name
     *
     * @param resourceName the value for resource_lock.resource_name
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_lock.node_info
     *
     * @return the value of resource_lock.node_info
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public String getNodeInfo() {
        return nodeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_lock.node_info
     *
     * @param nodeInfo the value for resource_lock.node_info
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public void setNodeInfo(String nodeInfo) {
        this.nodeInfo = nodeInfo == null ? null : nodeInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_lock.count
     *
     * @return the value of resource_lock.count
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_lock.count
     *
     * @param count the value for resource_lock.count
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_lock.desc
     *
     * @return the value of resource_lock.desc
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_lock.desc
     *
     * @param desc the value for resource_lock.desc
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_lock.update_time
     *
     * @return the value of resource_lock.update_time
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_lock.update_time
     *
     * @param updateTime the value for resource_lock.update_time
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_lock.create_time
     *
     * @return the value of resource_lock.create_time
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_lock.create_time
     *
     * @param createTime the value for resource_lock.create_time
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}