package com.xudaweb.distributed.lock.dal.dao;

import com.xudaweb.distributed.lock.dal.model.ResourceLock;
import com.xudaweb.distributed.lock.dal.model.ResourceLockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceLockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_lock
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    long countByExample(ResourceLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_lock
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    int deleteByExample(ResourceLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_lock
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_lock
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    int insert(ResourceLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_lock
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    int insertSelective(ResourceLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_lock
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    List<ResourceLock> selectByExample(ResourceLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_lock
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    ResourceLock selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_lock
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") ResourceLock record, @Param("example") ResourceLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_lock
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    int updateByExample(@Param("record") ResourceLock record, @Param("example") ResourceLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_lock
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    int updateByPrimaryKeySelective(ResourceLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_lock
     *
     * @mbg.generated Sat Oct 13 10:14:58 CST 2018
     */
    int updateByPrimaryKey(ResourceLock record);
}